site_name: Oscips e OS
site_url: https://seplagmg-parcerias.github.io/SCPTS-raiz/

nav:
  - index.md
  - oscip/index.md
  - os/index.md
  - capacitações/index.md
  - outrosdocs/index.md

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
  palette:
    - scheme: default
      primary: lime
      accent: teal
      toggle: 
        icon: material/brightness-4 
        name: Modo Escuro
    - scheme: slate
      primary: lime
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Modo Claro
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: octicons/git-compare-24

repo_name: seplagmg-parcerias/SCPTS-raiz
repo_url: https://github.com/seplagmg-parcerias/SCPTS-raiz
edit_uri: edit/main/docs/


 